version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    enviroment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/posrtgres
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:urs/app

volumes:
  pgdata:
    driver: local